### ISSUE TITLE
feature: Add example hosts file to readme

### ISSUE THREAD

**Issue by pakauffm** [lablabs/ansible-collection-wireguard#19]
### Summary

Could the contributors please provide a sample hosts file? When going through the role tasks and comparing them to the default parameters it is unclear which host is designated as the server with the 10.213.213.1 IP and which is designated as the client with 10.213.213.2, .3, .4, .... .254.

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Hi @pakauffm, this collection is configuring and connecting only to the wireguard server (or servers if you are configuring also a "standby" server).
